name: Publishes package to PyPi on release

on:
    # Runs on pushes targeting the default branch
    release:
      types: [published]
    workflow_dispatch:

jobs:
  build:
    name: Build Package using Hatch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Load cache
      uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('requirements-dev.txt') }}

    - name: Build package
      run: |
        make install-dev
        hatch build
    - name: Run unit tests
      run: make coverage
    - uses: actions/upload-artifact@v4
      with:
        name: opendataval-dist
        path: ./dist

  publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs: build
    environment: release
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    # retrieve your distributions here
    - uses: actions/download-artifact@v4
      name: opendataval-dist

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: opendataval-dist/
        repository-url: ${{ vars.REGISTRY_URL }}
        skip-existing: true
        verbose: true